stages:
  - build
  - test
  - deploy

# Build-Stage
build:
  image: docker:stable
  stage: build
  services:
    - docker:dind
  script:
    - docker build -t my-image .
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker tag my-image $CI_REGISTRY_IMAGE/my-image
    - docker push $CI_REGISTRY_IMAGE/my-image

# Test-Stage
test:
  image: node:14
  stage: test
  script:
    - npm install
    - npm test

# Deploy-Stage
deploy:
  image: docker:stable
  stage: deploy
  services:
    - docker:dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker pull $CI_REGISTRY_IMAGE/my-image
    - docker run --rm $CI_REGISTRY_IMAGE/my-image npm run migrate
    - docker stop $(docker ps -aq --filter name=my-container) || true
    - docker rm $(docker ps -aq --filter name=my-container) || true
    - docker run -d --name my-container -p 80:3000 $CI_REGISTRY_IMAGE/my-image